import 'package:flutter/material.dart';

// ignore: camel_case_types
class mainscreen extends StatelessWidget {
  const mainscreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Different Country Flags"),
        titleTextStyle: const TextStyle(fontSize: 30, color: Colors.white),
        backgroundColor: Colors.blue,
      ),
      body:
          // SizedBox(
          //   child:
          SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.black),
                    Container(width: 50, height: 50, color: Colors.yellow),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.black),
                    Container(width: 50, height: 50, color: Colors.black),
                    Container(width: 50, height: 50, color: Colors.black),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.yellow),
                    Container(width: 50, height: 50, color: Colors.yellow),
                    Container(width: 50, height: 50, color: Colors.yellow),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.black),
                    Container(width: 50, height: 50, color: Colors.yellow),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.green),
                    Container(width: 50, height: 50, color: Colors.green),
                    Container(width: 50, height: 50, color: Colors.green),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.black),
                    Container(width: 50, height: 50, color: Colors.yellow),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.yellow),
                    Container(width: 50, height: 50, color: Colors.yellow),
                    Container(width: 50, height: 50, color: Colors.yellow),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.blue),
                    Container(width: 50, height: 50, color: Colors.blue),
                    Container(width: 50, height: 50, color: Colors.blue),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.green),
                    Container(width: 50, height: 50, color: Colors.green),
                    Container(width: 50, height: 50, color: Colors.green),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.green),
                    Container(width: 50, height: 50, color: Colors.green),
                    Container(width: 50, height: 50, color: Colors.green),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.blue),
                    Container(width: 50, height: 50, color: Colors.blue),
                    Container(width: 50, height: 50, color: Colors.blue),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.green),
                    Container(width: 50, height: 50, color: Colors.green),
                    Container(width: 50, height: 50, color: Colors.green),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                  ],
                ),
                Row(
                  children: [
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.red),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                    Container(width: 50, height: 50, color: Colors.white),
                  ],
                ),
              ],
            ),
          ),
    );
  }
}
